cars/urls.py
from django.urls import path

from . import views

app_name = 'cars'

urlpatterns = [
    path('add_car/', views.AddCarView.as_view(), name='add-car'),
    path('car_profile/<int:pk>/', views.CarProfileView.as_view(), name='car-profile'),
    path('rent_car/<int:pk>/', views.car_rent_view, name='car_rent'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('', include('cars.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('search/', views.SearchResultsView.as_view(), name='car-search'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/my-cars/', views.MyCars.as_view(), name='my-cars'),
    path('profile/my-cars/return/', views.return_car, name='return-car'),
]

cars/models.py
import django.contrib.auth.models
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category


class Car(models.Model):
    car_brand = models.CharField(max_length=100)
    car_model = models.CharField(max_length=100)
    car_color = models.CharField(max_length=100)
    number_of_seats = models.CharField(max_length=100)
    number_of_doors = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='car_category')
    owner = models.ForeignKey(django.contrib.auth.models.User, on_delete=models.CASCADE, related_name='car_owner')
    is_rented = models.BooleanField(default=False)
    location = models.CharField(max_length=150, default=None)
    price_per_day = models.PositiveIntegerField(default=100)
    renter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='car_renter', null=True)

    def __str__(self):
        return self.car_model

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

cars/forms.py
from django import forms


class RentCarForm(forms.Form):

    days = forms.IntegerField()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password')
        help_texts = {
            'username': None,
            'email': None,
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))

        if commit:
            user.save()

        return user

cars/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, TemplateView
from django.contrib.auth.models import User

from cars import forms, models
from cars.forms import RentCarForm


class AddCarView(CreateView):
    model = models.Car
    fields = [
        'car_brand',
        'car_model',
        'car_color',
        'number_of_seats',
        'number_of_doors',
        'category',
        'owner',
        'location',
        'price_per_day',
    ]

    template_name = 'cars/add_car.html'
    raise_exception = False
    success_url = reverse_lazy('home:home')

    def get_form(self, *args, **kwargs):
        form = super(AddCarView, self).get_form(*args, **kwargs)
        form.fields['owner'].queryset = User.objects.all().filter(username=self.request.user.username)
        return form

    def form_valid(self, form):
        return super().form_valid(form)


class CarProfileView(DetailView):
    model = models.Car

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@login_required
def car_rent_view(request, pk):
    car = models.Car.objects.get(pk=pk)
    form = RentCarForm(request.POST)
    if form.is_valid():
        car.is_rented = True
        user = User.objects.get(pk=request.user.pk)
        car.renter = user
        car.save()
        return render(request, 'cars/car_rent_confirm.html')

    form = RentCarForm()
    return render(request, 'cars/car_rent.html', {'form': form})

home/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView
from cars.models import Car


def home_view(request):
    return render(request, 'home/landing-page.html')


class SearchResultsView(ListView):
    model = Car
    template_name = 'home/search-results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        category = self.request.GET.get('categories')
        object_list = Car.objects.all().filter(location=query, category=category)
        return object_list

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse
from django.views.generic import FormView, ListView

from cars.models import Car
from . import forms


class SignupView(FormView):
    form_class = forms.RegistrationForm
    template_name = 'users/signup.html'
    success_url = '/'

    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=True)
            user.is_active = True
            user.save()
        return super().form_valid(form)


@login_required
def profile_view(request):
    return render(request, 'users/profile.html')


class MyCars(ListView):
    model = Car
    template_name = 'users/users_cars.html'
    context_object_name = 'cars'

    def get_queryset(self):
        return Car.objects.filter(renter=self.request.user.pk)


def return_car(request):
    car = Car.objects.get(renter=request.user.pk)
    car.is_rented = False
    car.renter = None
    car.save()
    return render(request, 'cars/car_return_confirm.html')

cars/templates/cars/add_car.html
{% extends 'base.html' %}

{% block container %}
    <div class="add-car">
        <h1>Add your car</h1>
        <div class="add-car-form">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Add</button>
            </form>
        </div>
    </div>
{% endblock container %}

cars/templates/cars/car_detail.html
{% extends 'base.html' %}

{% block container %}
    <div class="car-profile">
        <h1>Car Profile</h1>
        <div class="car-profile-info">
            <ul>
            <li>
                Car Brand : {{ object.car_brand }}
            </li>
            <li>
                Car Model :  {{ object.car_model }}
            </li>
            <li>
                Car Color : {{ object.car_color }}
            </li>
            <li>
                Number of doors : {{ object.number_of_doors }}
            </li>
            <li>
                Number of seats : {{ object.number_of_seats }}
            </li>
            <li>
                Price per day: ${{ object.price_per_day }}
            </li>
        </ul>
        <a href="{% url 'cars:car_rent' pk=object.pk %}">
            <button type="submit" id="rent-car-button">Rent this car</button>
        </a>
        </div>
    </div>
{% endblock container %}

cars/templates/cars/car_rent.html
{% extends 'base.html' %}

{% block container %}
    <div class="background-opaque">
        <div class="background-shown">
            <h1>Rent</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Rent</button>
            </form>
        </div>
    </div>
{% endblock container %}

cars/templates/cars/car_rent_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
    <div class="rent-confirmation">
        <h1>Thank you for renting! Don't forget to return the car on return date</h1>
        <a href="{% url 'home:home' %}">
            Return to home page
        </a>
    </div>
{% endblock container %}

cars/templates/cars/car_return_confirm.html
{% extends 'base.html' %}

{% block container %}
    <h1>Thank you for returning your car on time!</h1>
{% endblock container %}

home/templates/home/landing-page.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
{% endblock styles %}

{% block container %}
        <div class="search-box">
            <h1>Rent a Car</h1>
            <div class="search-box-items">
                <form action="{% url 'home:car-search' %}" method="get" class="search-form">
                    {% csrf_token %}
                    <label for="city-search">
                        <input name='q' type="text" placeholder="Warsaw..." id="city-search" required>
                    </label>
                    <div class="search-box-items-select">
                        <label for="categories">
                            <select name="categories" id="categories">
                                <option value="1">SUV</option>
                                <option value="2">Combi</option>
                                <option value="3">Hatchback</option>
                                <option value="4">Sedan</option>
                                <option value="5">Offroad</option>
                            </select>
                        </label>
                    </div>
                    <div class="search-box-items-button">
                        <button type="submit" id="car-search-button">Search</button>
                    </div>
                </form>
            </div>

        </div>
{% endblock container %}

home/templates/home/search-results.html
{% extends 'base.html' %}

{% block container %}
    <div class="car-search-results">
    <h1 id="search-result-title">Search Results</h1>
        <div class="car-search-items">
            <ul>
                {% for car in object_list %}
                    {% if not car.is_rented %}
                        <li>
                            <a href="{% url 'cars:car-profile' pk=car.pk%}">{{ car.car_brand }} {{ car.car_model }}</a>
                        </li>
                        {% else %}
                            <h1>All cars seem to be rented for this category and city</h1>
                    {% endif %}
                    {% empty %}
                        <h1>No cars in this city yet</h1>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock container %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <title>{% block title %}Rent A Car{% endblock title %}</title>
</head>
<body>
{% include 'partials/navbar.html' %}
{% block container %}
{% endblock container %}
</body>
</html>

templates/partials/navbar.html
{% load static %}
<nav class="navbar">
    <ul>
        <li>
            <a href="/">Home</a>
        </li>
        {% if not user.is_authenticated %}
        <li>
            <a href="{% url 'users:signup' %}" id="signup-link">Signup</a>
        </li>
        <li>
            <a href="{% url 'login' %}" id="login-link">Login</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'logout' %}">Logout</a>
        </li>
        <li>
            <a href="{% url 'users:profile' %}">My Profile</a>
        </li>
        {% endif %}
    </ul>
</nav>

users/templates/users/profile.html
{% extends 'base.html' %}

{% block container %}
    <div class="my-profile">
        <h1>My Profile</h1>
        <div class="my-profile-items">
            <p><a href="{% url 'users:my-cars' %}">My rented cars</a></p>
            <p><a href="{% url 'password_change' %}">Change Password</a></p>
            <p><a href="{% url 'cars:add-car'%}">Add your car</a></p>
        </div>
    </div>
{% endblock container %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% block container %}
    <div class="signup-header">
        <h1>Signup</h1>
        <div class="signup-form">
            <form action="{% url 'users:signup' %}" method="post" class="login-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Signup</button>
            </form>
        </div>
    </div>

{% endblock container %}

users/templates/users/users_cars.html
{% extends 'base.html' %}

{% block container %}
    <div class="my_cars">
        {% for car in cars %}
            {{ car.car_brand }} {{ car.car_model }}
            <a href="{% url 'users:return-car' %}"><button>Return</button></a>
        {% empty %}
            <h1>No cars rented</h1>
        {% endfor %}
    </div>
{% endblock container %}